export const FETCH_TEST_SUITES_REQUEST =
    'FETCH_TEST_SUITES_REQUEST';
export const FETCH_TEST_SUITES_RECEIVE =
    'FETCH_TEST_SUITES_RECEIVE';
export const FETCH_TEST_RUNS_REQUEST =
    'FETCH_TEST_RUNS_REQUEST';
export const FETCH_TEST_RUNS_RECEIVE =
    'FETCH_TEST_RUNS_RECEIVE';
export const FETCH_TEST_SUITE_DATA_REQUEST =
    'FETCH_TEST_SUITE_DATA_REQUEST';
export const FETCH_TEST_SUITE_DATA_RECEIVE =
    'FETCH_TEST_SUITE_DATA_RECEIVE';
export const FETCH_TEST_RUN_SUMMARY_REQUEST =
    'FETCH_TEST_RUN_SUMMARY_REQUEST'
export const FETCH_TEST_RUN_SUMMARY_RECEIVE =
    'FETCH_TEST_RUN_SUMMARY_RECEIVE'
export const FETCH_TEST_RUN_DETAILS_REQUEST =
    'FETCH_TEST_RUN_DETAILS_RECEIVE'
export const FETCH_TEST_RUN_DETAILS_RECEIVE =
    'FETCH_TEST_RUN_DETAILS_RECEIVE'
