name: mypy

on: [pull_request]


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy types-protobuf==4.24.0.4
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: mypy
      run: |
        mkdir .mypy_cache -p
        mypy arthur_bench --ignore-missing-imports --install-types --non-interactive