# This workflow builds the arthur_bench/server/js directory and then builds the python 
# package and publishes to PyPi

name: Upload Python Package

on:  
  push:
    tags:
      - '*'

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        working-directory: arthur_bench/server/js
        run: npm i
      - name: Build
        working-directory: arthur_bench/server/js
        run: npm run build
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml twine
          pip install --upgrade build
      - name: Build package
        run: |
          python -m build --sdist --wheel --outdir dist
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
