name: test-frontend

on: 
  push:
    paths:
      - arthur_bench/server/js/**
      - .github/workflows/test-js.yml

  pull_request:
    paths:
      - arthur_bench/server/js/**
      - .github/workflows/test-js.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        working-directory: arthur_bench/server/js
        run: npm i
      - name: Build
        working-directory: arthur_bench/server/js
        run: npm run build
